# Generated by Django 4.0.3 on 2022-04-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_rename_title_todo_todo_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_title',
            new_name='top',
        ),
    ]
