# Generated by Django 4.0.3 on 2022-04-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_rename_todo_title_todo_top'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='top',
            new_name='title',
        ),
    ]
